name: Appearence
version: ${project.version}
main: appearence.appearence.Appearence
api-version: 1.19
authors: [ 481926paolo ]
description: this is a plugin that change weapon's appearence.
website: https://yejunscoding.tistory.com/
commands:
  μ™Έν•:
    usage: /μ™Έν•